add teamsection
hh-web-21-7/css-project-team3 pull request #8
Opened 2021-10-08 21:22 UTC by WaliedWeb

2021-10-09 05:54 UTC, Samet91 commented on style/components/teamsection.css
> +}
Its good

2021-10-09 07:44 UTC, F-Kirchhoff requested changes

2021-10-09 07:44 UTC, F-Kirchhoff commented on index.html
> +    </section>
use ul here, and style it with grid.

2021-10-10 11:36 UTC, F-Kirchhoff approved these changes

2021-10-10 11:36 UTC, merged